# Example ESPHome configuration using the camera web server with placeholder

substitutions:
  name: esp32-cam-placeholder-example
  friendly_name: ESP32 Camera with Placeholder

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Load the external component
external_components:
  - source: github://nickoe/esphome-esp32-camera-web-server-placeholder
    components: [ esp32_camera_web_server_placeholder ]

# Camera configuration (AI-Thinker model)
esp32_camera:
  id: my_camera
  name: Camera
  external_clock:
    pin: GPIO0
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  resolution: 800x600
  jpeg_quality: 10

# Web server with placeholder support
esp32_camera_web_server_placeholder:
  port: 8080
  mode: stream
  placeholder_enabled: true

# Optional: Add controls for camera power management
switch:
  - platform: gpio
    pin: GPIO32
    name: "Camera Software Power"
    id: camera_power
    restore_mode: ALWAYS_OFF
    internal: true

button:
  - platform: template
    name: "Restart Camera"
    on_press:
      - switch.turn_on: camera_power
      - delay: 100ms
      - switch.turn_off: camera_power
      - logger.log: "Camera reinitialized"